spring.application.name=authentication

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/authentication?createDatabaseIfNotExist=true
spring.datasource.username=root

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=migwambohamilton42@gmail.com
spring.mail.password=<EMAIL PASSWORD>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#pass = 72eb62fe-775f-4b69-b3ab-22876b7b6b13